# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='first_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), size=1),
        ),
    ]
